// English copy. Shape must mirror `es.js` exactly — the copy-coverage test
// enforces parity.

export const en = {
  partnerName: 'Ayuda Legal PR',
  builtBy: 'Built by La Mano',
  free: 'Free · Nonprofit',
  demo: 'Prototype — demo data',
  back: 'Back',
  disclaimer: 'Independent tool. Not affiliated with FEMA or the federal government.',
  crisisLine: 'Crisis or emergency: 911 \u00b7 Spanish crisis line 988',
  skipToContent: 'Skip to content',
  languageSwitch: 'Switch to Spanish',
  needHelp: 'Need other help?',
  needHelpSub: "Food, shelter, or you're in crisis — we can show you where to call.",

  consent: {
    title: 'Save your progress on this device',
    body: 'We can remember where you left off — on this phone, not online. You can clear it anytime.',
    accept: 'That\u2019s fine',
    decline: 'Don\u2019t save',
  },

  errorBoundary: {
    title: 'Something went wrong.',
    body: 'Your progress is saved. You can try again.',
    retry: 'Try again',
  },

  evidence: {
    whyLabel: 'Why?',
    progressLabel: 'evidence items complete',
    items: {
      photo: {
        title: 'A photo of your house',
        desc: 'Exterior and any damage. Phone photos work.',
        why: 'Shows the house exists and you have access to it. FEMA accepts timestamped photos.',
      },
      bill: {
        title: 'A bill with your name and address',
        desc: 'Electric, water, internet, or any recent account.',
        why: "Proves you live there. Doesn't need to be a deed — a bill with your name is enough.",
      },
      'mayor-letter': {
        title: 'Letter from the mayor or community board',
        desc: "If you don't have a bill, a letter from the municipio works.",
        why: 'FEMA accepts official letters from the municipio confirming you live there. We give you the template to request it.',
      },
      'neighbor-affidavit': {
        title: "Neighbor's sworn statement",
        desc: 'A neighbor signs saying you live there. We provide the template.',
        why: "Since 2021, FEMA accepts sworn statements when there's no deed. This is your safety net.",
      },
    },
  },

  landing: {
    eyebrow: 'FEMA appeals',
    headline: 'Did FEMA\ndeny your aid?',
    sub: 'We can help you appeal. Free. In 15 minutes, with one photo of your letter.',
    cta: 'Get started',
    note: 'We read your letter, prepare the appeal, and tell you exactly what to send to FEMA.',
    phoneLabel: 'Rather talk to someone?',
    phone: '1-800-981-5342',
  },

  upload: {
    step: 'Step 1 of 5',
    headline: 'Upload your\ndenial letter',
    sub: 'A photo from your phone is fine. PDF works too.',
    dropTitle: 'Take a photo or upload a file',
    dropSub: 'We read letters in English or Spanish automatically',
    camera: 'Take photo',
    upload: 'Upload file',
    reassure: 'Your documents are private. No one else sees them.',
    demo: 'Use demo letter',
    manualEntry: 'Enter details by hand',
    fileInputLabel: 'Select denial letter',
  },

  processing: {
    headline: 'Reading your letter\u2026',
    sub: 'This takes about 20 seconds.',
    tasks: [
      'Finding the case number',
      'Identifying denial reason',
      'Calculating appeal deadline',
      'Checking what evidence you need',
    ],
  },

  login: {
    step: 'Your account',
    headline: 'Sign in to\nsave your case',
    sub: "We'll send you a link by email. No password needed.",
    emailLabel: 'Your email address',
    emailPlaceholder: 'you@example.com',
    cta: 'Send me the link',
    sending: 'Sending\u2026',
    sentHeadline: 'Check your email',
    sentSub: 'We sent a link to {email}. Tap it to continue.',
    sentNote: "If you don't see it, check your spam folder.",
    privacy: 'We only store what\u2019s needed for your appeal. You can delete everything at any time.',
  },

  manualEntry: {
    step: 'Letter details',
    headline: 'Enter the\ndetails by hand',
    sub: "We couldn't read the photo automatically. Enter the date and code from your letter.",
    dateLabel: 'Date of denial letter',
    codeLabel: 'Denial code',
    code120: '120 \u2014 Ownership not verified',
    code203: '203 \u2014 Occupancy not verified',
    code204: '204 \u2014 Duplication of benefits',
    codeOther: 'Other / I don\u2019t know',
    nameLabel: 'Your name (optional)',
    namePlaceholder: 'As it appears on the letter',
    daysLeft: '{n} days to appeal',
    overdue: 'Appeal deadline has passed',
    unsupportedCode: "We can't prepare this appeal automatically yet. Call Ayuda Legal PR: 1-800-981-5342.",
    otherResources: 'See other help resources',
    cta: 'Continue',
    saving: 'Saving\u2026',
  },

  diagnosis: {
    step: 'Step 2 of 5',
    headline: "Here's what\nwe found",
    caseLabel: 'Your case',
    disasterLabel: 'The disaster',
    reasonLabel: 'Reason for denial',
    deadlineLabel: 'Appeal deadline',
    daysLeft: 'days left',
    deadlineDate: 'due',
    overdue: 'Deadline passed',
    noDate: 'Date not available',
    reasonPlain: "FEMA says you didn't prove you own the house.",
    reasonContext:
      "This is the most common denial in Puerto Rico. 35% of homes don't have formal title. It's appealable, and FEMA accepts other ways to prove ownership — you don't need a deed.",
    appealableBadge: 'Appealable',
    cta: 'Prepare my appeal',
    overdueCta: 'See what else I can do',
  },

  evidenceScreen: {
    step: 'Step 3 of 5',
    headline: 'We need\nthese things',
    sub: "For your denial type, this evidence is what convinces FEMA. We'll walk you through each one.",
    optional: 'Optional — but helps',
    addButton: 'Upload',
    done: 'Done',
    template: 'See template',
    cta: 'I have everything',
    skipLater: 'I can upload later',
  },

  draft: {
    step: 'Step 4 of 5',
    headline: 'Your appeal\nis ready',
    sub: 'Reviewed by an Ayuda Legal PR attorney. Ready to send to FEMA.',
    reviewBadge: 'Attorney-reviewed',
    draftBadge: 'Draft',
    previewLabel: 'Letter preview',
    letterAriaLabel: 'Appeal letter draft',
    switchTo: 'Ver en español',
    generating: 'Preparing your letter\u2026',
    cta: 'Send to FEMA',
    disclaimer:
      'Appeals are sent in English because FEMA processes English faster. We keep the Spanish version for you.',
  },

  submit: {
    step: 'Step 5 of 5',
    headline: 'Send the appeal\nto FEMA',
    sub: 'Three ways. Pick what works for you.',
    methods: [
      {
        title: 'Online',
        badge: 'Fastest',
        steps: [
          'Go to disasterassistance.gov',
          'Log in to your account',
          'Go to "Correspondence"',
          'Upload the file we give you',
          'Tap "Submit"',
        ],
        cta: 'Download file',
      },
      {
        title: 'By mail',
        badge: 'Paper option',
        steps: [
          'Print the letter and evidence',
          'Put it in an envelope with the label we provide',
          'Mail it before the deadline',
        ],
        cta: 'Download envelope & label',
      },
      {
        title: 'By fax',
        badge: 'Traditional',
        steps: [
          'Use the fax at the nearest Recovery Center',
          'The fax number is in the file we give you',
        ],
        cta: 'See fax numbers',
      },
    ],
    confirm: "I've sent it",
    help: 'Need help? Call us: 1-800-981-5342',
  },

  admin: {
    queueTitle: 'Review queue',
    pendingSuffix: 'pending',
    queueEmpty: 'Queue is empty. All caught up.',
    queueError: 'Queue error',
    queueLoadingLabel: 'Loading pending cases',
    unknownApplicant: 'Unknown applicant',
    overdue: 'Overdue',
    daysLeftShort: '{n}d left',
    backToQueue: 'Queue',
    caseShort: 'Case {id}',
    caseHeader: 'Case {id} \u00b7 Draft v{v}',
    englishDraftHeader: 'English draft (sent to FEMA)',
    spanishDraftHeader: 'Spanish draft (applicant copy)',
    englishDraftAria: 'English appeal draft',
    spanishDraftAria: 'Spanish appeal draft',
    englishDraftEmpty: '(no English body)',
    editHint: 'You can also edit the Spanish draft above before submitting.',
    approve: 'Approve',
    requestChanges: 'Request changes',
    reject: 'Reject',
    cancel: 'Cancel',
    caseOrDraftMissing: 'Case or draft not found.',
    caseNotFound: 'Case or draft not found.',
    backLabel: 'Back',
    approveNotesPlaceholder: 'Optional notes for the record\u2026',
    requestChangesPlaceholder: 'Describe what needs to change (required)\u2026',
    rejectPlaceholder: 'Reason for rejection (required)\u2026',
    confirmApprove: 'Confirm approve',
    confirmReject: 'Confirm reject',
    sendFeedback: 'Send feedback',
    approving: 'Approving\u2026',
    rejecting: 'Rejecting\u2026',
    submitting: 'Submitting\u2026',
    sidebar: {
      deadline: 'Deadline',
      deadlinePassed: 'Appeal deadline has passed',
      daysRemaining: '{n} days remaining',
      dateUnavailable: 'Date not available',
      letterDate: 'Letter date: {date}',
      denial: 'Denial',
      denialCode: 'Code:',
      disaster: 'Disaster:',
      applicant: 'Applicant',
      applicantMissing: 'Name not recorded',
      citations: 'Required citations',
      model: 'Model',
      versionPrefix: 'v',
      draftQuality: 'Draft source',
      draftQualityCodeSpecific: 'Code-specific guidance',
      draftQualityGeneral: 'General framework \u2014 review with extra care',
    },
  },

  resources: {
    step: 'Other resources',
    headline: 'Other help\nthat exists today',
    sub: "If what you need right now isn't an appeal — or your deadline has passed \u2014 these lines are free and answer in Spanish and English.",
    disclaimer: 'We are not these organizations. We just point you to where they are.',
    callLabel: 'Call',
    visitLabel: 'Website',
    back: 'Back to home',
    sections: [
      {
        id: 'crisis',
        title: 'Crisis right now',
        body: "If you're in danger or thinking about harming yourself, call before anything else.",
        items: [
          { label: '911 \u2014 emergencies', phone: '911', note: 'Police, fire, ambulance' },
          { label: '988 \u2014 crisis line', phone: '988', note: 'Spanish available 24/7' },
          { label: 'SAMHSA \u2014 disaster distress', phone: '1-800-985-5990', note: 'Free, confidential, 24/7' },
        ],
      },
      {
        id: 'shelter',
        title: 'Shelter and federal help',
        body: 'Emergency shelters, your FEMA case status, disaster assistance questions.',
        items: [
          { label: 'Red Cross', phone: '1-800-733-2767', url: 'https://www.redcross.org/get-help/disaster-relief-and-recovery-services.html', note: 'Shelter and immediate needs' },
          { label: 'FEMA main line', phone: '1-800-621-3362', url: 'https://www.disasterassistance.gov', note: 'Application status, letter questions' },
        ],
      },
      {
        id: 'food',
        title: 'Food and basic services',
        body: 'Food banks, D-SNAP, drinking water, local assistance.',
        items: [
          { label: '211 \u2014 services directory', phone: '211', url: 'https://www.211.org/', note: 'Available 24/7, Spanish available' },
        ],
      },
      {
        id: 'legal',
        title: 'Other legal help',
        body: "If your case isn't about FEMA, or you need an attorney.",
        items: [
          { label: 'Ayuda Legal Puerto Rico', phone: '1-800-981-5342', url: 'https://www.ayudalegalpr.org', note: 'Free for low-income families' },
        ],
      },
    ],
  },

  tracking: {
    step: 'Done',
    headline: 'Sent',
    sub: 'FEMA has 90 days to respond. We text you when there are updates.',
    submittedLabel: 'Submitted',
    expectedLabel: 'Response expected',
    caseLabel: 'Your case number',
    smsLabel: 'SMS reminders',
    nextSteps: "What's next?",
    stepsList: [
      'FEMA reviews the appeal (30–90 days)',
      'If approved, they send the funds',
      "If they need more info, we'll let you know",
      'If denied again, we can prepare a second appeal',
    ],
    another: 'Help someone else',
  },
}
